language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: g7el8SmgCBnwRxF2++te6CA/mhXJ62iu1cSFPV1acFRwjKs/2I/F/XvFCdo/9FeoYWNDm15gGqtrUX4OVVYxSzvfSCT6AozhXVdjjgiN52HY4xziok0x3QmK9CYbZ3qlUTyyV6q3bP9KLwS2a9S8j8bjPDmUeBINyvOQSw0F1f/Ip0O6y3hvltbbzCw3NSmvyQIsRaAtvE8f9AEOYKg6QYFgg3uzKTeKqbsx/8l/Ii0vhteK1MddzT+9y157F6PdBCqi3qDWDuSJzEqYdA8bpWQ5JvK68Zy6gmv24aCloFJ3Yjd2GF04SuusBKYEJYvDz+iPNQAxc1tUS9d9I3ETWqduJzu5Bqymmluud0yQNPp1kOG2EmSxnRFBhluuBIzZLIiDecReoqC9SkjOE83kIDopR7xDSwtQX4lisTjuXsZJisrEMlRBoX4MJXx2G8n1pL0G5Q9CtvQYL3Tg2DIBj0yuRsVhX3Wf42TxSDMh6KgMWiQqltTOrBSlE/tu+gDXJ8uWyhCk937kIA/sqDO2dDyfxekiIuwIB+xA/KXRiTqI2kLEha7gdXtsBufw7WjoLtBfL7uVGaIsedIV4UcmIQdGoV1uXj2BZjvbeTErIICVtUUoOeXjQ2aSAzIp6ZrVgUlHQgpTvkGXN2409pleRu+pAm5gUbvVMtcW12GFLo0=
